server:
  port: 8000
eureka:
 instance:
   non-secure-port: ${server.port}
   instance-id: ${spring.cloud.client.ip-address}:${server.port}
 client:
   service-url:
     defaultZone: http://admin:admin@localhost:8761/eureka/
   fetch-registry: true  
spring:
  cloud:
    zuul:
      oauth-server:
        path: /oauth/**
